services:
  server:
    container_name: prakticum-server
    image: prakticum-server
    build:
      context: .
      dockerfile: server.dockerfile
      args:
        NODE_VERSION: 20
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      POSTGRES_PORT_CONNECTION: ${POSTGRES_PORT_INTERNAL}
      POSTGRES_HOST: 'postgres'
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - db

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT_INTERNAL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      CSRF_PROTECTION: 'False'
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env
    networks:
      - db
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  db:
    driver: bridge
